# Generated by Django 5.1.7 on 2025-03-26 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_budget"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField()),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("one_time", "One-Time"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("bi_weekly", "Bi-Weekly"),
                            ("monthly", "Monthly"),
                            ("bi_monthly", "Bi-Monthly (Every Two Months)"),
                            ("quarterly", "Quarterly (Every 3 Months)"),
                            ("tri_monthly", "Tri-Monthly (Every 3 Months)"),
                            ("semi_annual", "Semi-Annual (Every 6 Months)"),
                            ("annual", "Annual (Yearly)"),
                            ("custom", "Custom (User Defined)"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "custom_cycle_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Applicable only if 'Custom' cycle is selected.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-due_date"],
            },
        ),
    ]
