# Generated by Django 5.1.7 on 2025-03-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_investmentcategory_investment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="img_url",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
